### ISSUE TITLE
Does it need an additional track module to track agents cross different video frames?

### ISSUE THREAD

**Issue by yt7589** [hustvl/VAD#1]
Does Vectored Motion Transformer module has the multi object track capability? If I want to track the agents cross different frames, should I add an additional track module such as TrackFormer to track these agents.

**Comment by rb93dett** [comment]
No, Vectorized Motion Transformer doesn't perform tracking, the future motion is predicted based on the implicit history features. You need to add an additional tracking module in order to perform tracking.
