### ISSUE TITLE
code checking

### ISSUE THREAD

**Issue by xinfu607** [hustvl/VAD#10]
Hi,
Thanks a lot for your code! I want to check if the code is typos ("for id in tqdm(len(sample_token_list)):"). https://github.com/hustvl/VAD/blob/6f3421b995b663b6308633d26978825282360e35/tools/analysis_tools/visualization.py#L745C1-L746C1.

Best,
Fu Xin

**Comment by rb93dett** [comment]
Yes, that's a typo and we have fixed it in the latest commit. Thank you for pointing it out!
