### ISSUE TITLE
CARLA Pipeline

### ISSUE THREAD

**Issue by georgeliu233** [hustvl/VAD#12]
Hi,

Thank you a lot for your code sharing. It is an insightful work for e2e AD task!
I am wondering whether do you plan to release the train & eval pipeline for CARLA benchmark?
I would appreciate a lot if you can also release this training pipieline.

Best

**Comment by rb93dett** [comment]
Thank you for your interest in VAD. Closed-loop pipeline is still under development, but the train&eval pipeline of VAD is very similar to Transfuser, you can just refer to their code https://github.com/autonomousvision/transfuser.

**Comment by raozhongyu** [comment]
Thanks for your great work. I'd like to konw how to bulid the dataset of carla and whether to release the dataset on carla model?

**Comment by rb93dett** [comment]
Carla dataset is built in a similar manner to nuScenes but requires additional pre-processing steps due to differences in the source data format.
The Carla pipeline is still under development, we will try to release it as soon as possible.

**Comment by raozhongyu** [comment]
Thanks a lot. Looking forward !

**Comment by Wolfybox** [comment]
is there a release plan for Carla pipeline and its pretrained weights？

**Comment by xiaodongww** [comment]
@rb93dett hi, is there any instructions on how to build carla dataset by myself? Thanks a lot.
