### ISSUE TITLE
Hard to install

### ISSUE THREAD

**Issue by PointsCoder** [hustvl/VAD#13]
Hi,

Thanks for your great work. I found it hard to install all the packages, because PyPI tried to install the latest versions of all packages if not specified. Some installed packages are not compatible with the mmdet version 0.17  (seems to be an old version). 

Would you mind exporting all package versions to requirements.txt? Like this:
`pip freeze > requirements.txt` or
`conda list -e > requirements.txt`

In this way I can install the correct versions of all packages.
Thanks!

**Comment by rb93dett** [comment]
Thanks for the suggestion :) we have updated the [requirements.txt](https://github.com/hustvl/VAD/blob/main/requirements.txt). Please take a look.
