### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by alfredgu001324** [hustvl/VAD#14]
Hi, thanks for the great work! I am using a RTX 4090 and the training of stage 1 shows that it would take approximately 15 days. I am wondering if this is normal that it will take so long? If I do end-to-end or 2-stage, what will be the approximate training time?

Since I am more curious about the performance of prediction, is it possible that you can release the checkpoint for stage 1? 

Thank you so much for your great work and looking forward to your reply!

**Comment by rb93dett** [comment]
As a reference, we use 8 RTX 3090 and batch size 1, and it took approximately 4 days to complete 48 epochs of training. When the training epochs are the same, the training time for end-to-end and staged training is similar.

The motion prediction performance is similar for stage-1 and stage-2, you can just use the released checkpoint to evaluate the motion performance.

**Comment by alfredgu001324** [comment]
I see, thank you so much
