### ISSUE TITLE
 how to generate the Vectorized ground truth 

### ISSUE THREAD

**Issue by raozhongyu** [hustvl/VAD#16]
Thanks  for your great job. I'd like to konw how to generate the Vectorized ground truth of  the Carla simulator?

**Comment by rb93dett** [comment]
The core data processing steps for generating vectorized ground truth are released in the [dataset](https://github.com/hustvl/VAD/blob/main/projects/mmdet3d_plugin/datasets/nuscenes_vad_dataset.py#L520) file and the [data converter](https://github.com/hustvl/VAD/blob/main/tools/data_converter/vad_nuscenes_converter.py) file. For generating GT on carla, you only need to perform some additional pre-processing steps to align carla's source data format with that of nuScenes.

The carla pipeline is still under development. Currently, we do not have plans to release the code on carla, but we will try to make it open-source as soon as possible.

**Comment by raozhongyu** [comment]
Thanks a lot.
