### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by ZhoubinXM** [hustvl/VAD#17]
Thank you very much for the valuable work of your team, I found out when I reproduced your code, since I couldn't open the URL of the train and val pkl files, I generated the corresponding pkl files through the data converter, but when I trained, a series of `shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)`, and then the training program terminates, here is my training log:[](url)
[file.txt.zip](https://github.com/hustvl/VAD/files/12554765/file.txt.zip)
Looking forward to hearing from you!

**Comment by yuyuyuyuyuty** [comment]
I have the same problem as you. Have you solved the problem? Can you tell me where the problem is? thank you.

**Comment by wzn0828** [comment]
Hi， 
I have the same problem as you. Have you solved the problem? Can you tell me where the problem is? thank you.

**Comment by wzn0828** [comment]
@ZhoubinXM 
Hi, I have the same problem as you. Have you solved the problem? Can you tell me where the problem is? thank you.
