### ISSUE TITLE
How to get onnx file of the whole model

### ISSUE THREAD

**Issue by hollyaoyaozi** [hustvl/VAD#20]
Hi, I'm going to transform .pth into .onnx but find provided .pth file only contains weights/bias.
So is it possible for your team to upload .pth file with the whole model (.onnx is more preferred) ?
thanks!

**Comment by rb93dett** [comment]
Hi, you can load the provided weight to the model and use `torch.save(model, 'net.pth')` to get the whole model (including model structure and weights). Please try it out : )

**Comment by hollyaoyaozi** [comment]
> Hi, you can load the provided weight to the model and use `torch.save(model, 'net.pth')` to get the whole model (including model structure and weights). Please try it out : )

Thank you for the reply. 
I want to use .onnx file for visualization of net structure by visualization tool like netro, and .pth seems not to be supported well by neron (the method you supplied above does not work either). And I tried to save the model into .onnx file using torch.onnx.export(), but failed (it seems that the 3rd-party lib like mmdet can not be recognized well ?). 
So how can i see the whole structure of VAD using any visualization tools ?

**Comment by rb93dett** [comment]
We haven't tried to visualize the model structure of VAD using any visualization tools, maybe like you said, VAD is bulit upon the mmdet environment and it is not friendly for the current visualization tools. Maybe you can try to find a solution by google it and see if others meet similar problems.

**Comment by hollyaoyaozi** [comment]
> We haven't tried to visualize the model structure of VAD using any visualization tools, maybe like you said, VAD is bulit upon the mmdet environment and it is not friendly for the current visualization tools. Maybe you can try to find a solution by google it and see if others meet similar problems.

OK，Thanks a lot~
