### ISSUE TITLE
what the lcf means?

### ISSUE THREAD

**Issue by yongguanjiangshan** [hustvl/VAD#22]
hi, in vad_nuscenes_converter.py. you've calculated the agent lcf feat. what the "lcf" means? looking forward your reply. thank you!

**Comment by rb93dett** [comment]
Hi, lcf means last context frame, agent_lcf_feat includes some status features (e.g., speed, yaw) of the corresponding agent in the current timestamp.

**Comment by yongguanjiangshan** [comment]
> Hi, lcf means last context frame, agent_lcf_feat includes some status features (e.g., speed, yaw) of the corresponding agent in the current timestamp.

OK, i got it, thank you!
