### ISSUE TITLE
how to get the driving command during infering phase?

### ISSUE THREAD

**Issue by yongguanjiangshan** [hustvl/VAD#25]
hi, could you please tell us how to get the driving command during infering phase?

**Comment by rb93dett** [comment]
In the open-loop nuScenes setting, driving commands are determined based on the ground truth ego future trajectories (Details see this [file](https://github.com/hustvl/VAD/blob/main/tools/data_converter/vad_nuscenes_converter.py#L452)). In the closed-loop CARLA setting, navigation information (sparse navigation points and driving commands) is generated through a global navigator.

**Comment by yongguanjiangshan** [comment]
> In the open-loop nuScenes setting, driving commands are determined based on the ground truth ego future trajectories (Details see this [file](https://github.com/hustvl/VAD/blob/main/tools/data_converter/vad_nuscenes_converter.py#L452)). In the closed-loop CARLA setting, navigation information (sparse navigation points and driving commands) is generated through a global navigator.

hi, in the infering phase, we don't have the ground truth. then how to get the commands?

**Comment by yongguanjiangshan** [comment]
thank you! do you mean that we have a global route at first. Then in the intersection area for example, we have already knowed the car's direction to go straight or turn left/right. am I right?

**Comment by rb93dett** [comment]
> thank you! do you mean that we have a global route at first. Then in the intersection area for example, we have already knowed the car's direction to go straight or turn left/right. am I right?

Yes, exactly.
