### ISSUE TITLE
Carla训练下的Map元素lane divider, road boundary, and pedestrian crossing提取

### ISSUE THREAD

**Issue by lsrrrrrrrrr** [hustvl/VAD#27]
打扰了，文章中提到了在vectorized map中使用了 lane divider, road boundary, and pedestrian crossing 三种元素。这几个元素在carla里训练时 是如何提取的？ 同时是以何种方式加入到训练数据集中的呢？

**Comment by lsrrrrrrrrr** [comment]
same with the issue https://github.com/hustvl/VAD/issues/16

**Comment by raozhongyu** [comment]
你好，我想问下这个问题你解决了吗

**Comment by jiaxiaosong1002** [comment]
@lsrrrrrrrr @raozhongyu  Hi, we are the authors of Bench2Drive and we would like to introduce that we have implemented VAD (non-official) in CARLA with code, checkpoints, and closed-loop results open sourced. Feel free to try it. https://github.com/Thinklab-SJTU/Bench2DriveZoo/tree/uniad/vad

**Comment by raozhongyu** [comment]
Thinks a lot.



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xiaosong Jia ***@***.***&gt;
发送时间: 2024年6月11日 18:47
收件人: hustvl/VAD ***@***.***&gt;
抄送: raozhongyu ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [hustvl/VAD] Carla训练下的Map元素lane divider, road boundary, and pedestrian crossing提取 (Issue #27)





 
@lsrrrrrrrr @raozhongyu  Hi, we are the authors of Bench2Drive and we would like to introduce that we have implemented VAD (non-official) in CARLA with code, checkpoints, and closed-loop results open sourced. Feel free to try it. https://github.com/Thinklab-SJTU/Bench2DriveZoo/tree/uniad/vad
