### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by wljungbergh** [hustvl/VAD#3]
Hi. Thanks for a great paper. 

Do you have an estimate of when you will release the code?

**Comment by sgzqc** [comment]
+1

**Comment by outsidercsy** [comment]
Sorry for the late reply. Code will be released in around two weeks.

**Comment by may210297** [comment]
Hi, it's about two weeks since the above reply. How is it now?

**Comment by rb93dett** [comment]
We just release the code, please check it out :), and thank you for your patience.

**Comment by may210297** [comment]
Thank you all！
