### ISSUE TITLE
Why ego_his_encoder and ego_lcf_feat_idx are None in the config?

### ISSUE THREAD

**Issue by buaazeus** [hustvl/VAD#30]
Why ego_his_encoder and ego_lcf_feat_idx are None in the config? The velocity and trajectory of ego vehicle are not used?
Thank you.

**Comment by rb93dett** [comment]
Yes, VAD does not use status features to conduct a fair comparison with other methods, but you can try it yourself by activating ego_his_encoder and ego_lcf_feat_idx.

**Comment by buaazeus** [comment]
Got it, thanks.
