### ISSUE TITLE
Question About Environment Building

### ISSUE THREAD

**Issue by Valerianding** [hustvl/VAD#51]
Hi Thanks for your great work. But When I am downloading the mmdet3D
```
conda activate vad
git clone https://github.com/open-mmlab/mmdetection3d.git
cd /path/to/mmdetection3d
git checkout -f v0.17.1
python setup.py develop
```

I came accross a problem:

```
error: networkx 2.2 is installed but networkx>=2.8 is required by {'scikit-image'}
```

I tried to download the networkx ==2.8 using pip & ran the python again. But it seems to remove my downloaded version every time. What Can I do. Thanks!

**Comment by Valerianding** [comment]
This is solved by install scikit-image using pip. And similar Problems should work well too

**Comment by zhangqiangbing** [comment]
hello, which version fo scikit-image should be installed?
