### ISSUE TITLE
Can This Be eval on nuScenes mini dataset?

### ISSUE THREAD

**Issue by Valerianding** [hustvl/VAD#52]
Since the full data set is too large. I wonder if this can be evaluated on nuScenes mini dataset?

cause When I am using mini dataset I encountered a problem:
```
FileNotFoundError: img file does not exist: ./data/nuscenes/samples/CAM_FRONT/n015-2018-07-11-11-54-16+0800__CAM_FRONT__1531281439762460.jpg
```
And I don't know how to solve this

**Comment by Valerianding** [comment]
This could be done by gernerating new pkl

**Comment by tangyipeng100** [comment]
I have tried to evaluate on nuScenes mini dataset, but the eval result does not seem to be good, have you got the results? thx
