### ISSUE TITLE
model output isn't correct format

### ISSUE THREAD

**Issue by nathaneilsam** [hustvl/VAD#71]
The format of model output don't include 'bbox_results' or 'mask_results',or the output don't include the nuscense's token?
![21e54054-5611-413a-a357-2d3dccb562c9](https://github.com/user-attachments/assets/887194d0-a832-4795-b868-fc1248a7f7e6)

so that   the line of visualization:  sample_token_list = list(bevformer_results['bbox_result'].keys()) cannot obtain the nuscense's token.

**Comment by MargeryLab** [comment]
how to solve it?
