### ISSUE TITLE
AttributeError: 'numpy.int64' object has no attribute 'intersects'

### ISSUE THREAD

**Issue by MRYUjg** [hustvl/VAD#73]
Hello, when I was testing the dataset, although I successfully obtained some test results, 

![2024-08-16 20-46-42 的屏幕截图](https://github.com/user-attachments/assets/366a36e4-9a91-4d34-b61a-2612c121b431)
I also encountered these errors in the follow-up, it seems that the code has a data format problem, can you answer it for me?
![2024-08-16 20-47-47 的屏幕截图](https://github.com/user-attachments/assets/aa3f6e1a-565c-41d9-bdc4-59342a7ac2e3)

**Comment by whhyda** [comment]
This has been addressed earlier, you can take a closer look at issues

**Comment by MRYUjg** [comment]
Thanks, I see that the previous issue has been resolved
