### ISSUE TITLE
Wrong 'img_norm_cfg' setting

### ISSUE THREAD

**Issue by zhiqi-li** [hustvl/VAD#9]
It seems that you used the wrong `img_norm_cfg` for the resnet50 (pytorch format). 

It should be
 ``` 
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
```

**Comment by rb93dett** [comment]
Thank you for pointing out : ), we have updated the configs to use the right img_norm_cfg.

**Comment by tyzhi** [comment]
I  noticed that the `img_norm_cfg`  is the same to that of UniAD .   Could you please explain whether it will affect model's performance?
